data:
  download_path: "../data/downloaded_dataset"       

robowflow:
  workspace: "cv-uoacw"
  project: "playingcarddetection-tea12-whczv"
  version: 1

model:
  type: "yolov8"
  variant: "n"  # n, s, m, l, x (nano, small, medium, large, xlarge)
  weights: null  # path to custom weights, or null for pretrained
  conf_threshold: 0.25
  iou_threshold: 0.45
